language: objective-c
osx_image: xcode15.0.1
before_install:
    - brew upgrade cocoapods
deploy:
  provider: script
  script: sh run_tests.sh
  on:
    branch: master
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - htq287@gmail.com
    on_success: never
    on_failure: always